In [1]:
from sklearn import ensemble, model_selection, metrics ,datasets,tree
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
import numpy as np
import pandas as pd
digits=datasets.load_digits()
bc=datasets.load_breast_cancer()
digits.data[:10]
b = np.zeros(5)
c = np.diag(np.arange(2, 7, dtype = float))
res = (b + c)[:, np.newaxis]
print(res)

[[[2. 0. 0. 0. 0.]]

 [[0. 3. 0. 0. 0.]]

 [[0. 0. 4. 0. 0.]]

 [[0. 0. 0. 5. 0.]]

 [[0. 0. 0. 0. 6.]]]


In [45]:

train_data, test_data, train_labels, test_labels = model_selection.train_test_split(digits.data, digits.target)
gnd=GaussianNB()
bnb=BernoulliNB()
mnb=MultinomialNB()
gnd.fit(train_data,train_labels)
bnb.fit(train_data,train_labels)
mnb.fit(train_data,train_labels)

print cross_val_score(gnd,test_data, test_labels).mean()
print cross_val_score(bnb,test_data, test_labels).mean()
print cross_val_score(mnb,test_data, test_labels).mean()

0.7824741648642153
0.8044039894256189
0.8842525835135785


In [48]:

train_data, test_data, train_labels, test_labels = model_selection.train_test_split(bc.data, bc.target)
gnd=GaussianNB()
bnb=BernoulliNB()
mnb=MultinomialNB()
gnd.fit(train_data,train_labels)
bnb.fit(train_data,train_labels)
mnb.fit(train_data,train_labels)

print cross_val_score(gnd,test_data, test_labels).mean()
print cross_val_score(bnb,test_data, test_labels).mean()
print cross_val_score(mnb,test_data, test_labels).mean()

0.9651179620784484
0.5944420321320018
0.929656969170647
